name       : anoise 
version    : 0.0.25
release    : 1
source     :
    - https://launchpad.net/anoise/0.0.x/0.0.x/+download/anoise_0.0.25.tar.gz : c9a3c7d4d1b930d2cac98551427ea5e15235f0e27a82548edf5a0e4ded8e342a
license    : GPL-3.0
component  : multimedia.audio
summary    : Minimal and integrated ambient noise player for boosting productivity
description: Minimal and integrated ambient noise player for boosting productivity

builddeps  :
    - pkgconfig(gstreamer-0.10)
    - python-distutils-extra
rundeps:
    - anoise-media 
build      : |
    %apply_patches
    %python_setup
install    : |
    %python_install
